Features
ricardo123321/youtube-front-page pull request #1
Opened 2020-02-19 19:28 UTC by ricardo123321

2020-02-19 19:31 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-02-19 19:32 UTC, addod19 commented
> _No description provided._

Your project will be marked as invalid if you do not have a title and a short summary describing the work you did. Check [link here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

2020-02-19 20:05 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi @ricardo123321 and @tacodtripe you have done a great job in your first attempt 👍 . However, there are a few changes we need to make. Find comments below:
- Kindly fix the errors returned by [HTML markup](https://validator.w3.org/)
![p1](https://user-images.githubusercontent.com/46388113/74869323-ad1b7100-534f-11ea-840c-9aeb32931a53.PNG)
- README file should look professional check [link here](https://github.com/microverseinc/readme-template). The project will be marked as invalid if your README file does not look professional and PR [check link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) does not have a title and a short summary. Keep in mind 💭 
- The nav is missing this
![p2](https://user-images.githubusercontent.com/46388113/74869736-6e39eb00-5350-11ea-94c8-53e8ef527f9b.PNG)
Reference this
![p3](https://user-images.githubusercontent.com/46388113/74869816-91fd3100-5350-11ea-9c05-3b4a7adaf2e4.PNG)
- Currently, the UI does not look good. There is a horizontal scroll.
- Currently, the video section looks like this
![p4](https://user-images.githubusercontent.com/46388113/74870733-1dc38d00-5352-11ea-854e-6df9652babfe.PNG)
```Original``` Let us arrange it nicely like this
![p5](https://user-images.githubusercontent.com/46388113/74870779-32a02080-5352-11ea-9fe7-7d9b00958bdd.PNG)
- Set the nav ```width:100%``` it covers the entire width.
[OPTIONAL]
- The ```<aside>``` section can be improved

Make these changes and submit another code review 🙂 
Happy coding 💻 
Good luck with your next submission
Daniel Larbi Addo

2020-02-19 20:05 UTC, addod19 commented on index.html
> +    <div id="side-section">
Let us improve semantics by using ```<aside>``` instead of ```<div id="side-section">```. It is best practice to use classes for styling.

2020-02-19 20:05 UTC, addod19 commented on index.html
> +    </div>
All this part could be wrapped in a ```<footer>``` to improve semantics. The footer should be outside the closing ```<section>``` in ```line 133```

2020-02-19 20:05 UTC, addod19 commented on index.html
> +        </div>
This part could be wrapped in ```<main>``` up to ```line 114``` to improve semantics

2020-02-19 20:05 UTC, addod19 commented on style.css
> +      margin: 2em 12em;
Kindly remove the margin. It is breaking the page

2020-02-19 20:05 UTC, addod19 commented on style.css
> +    min-width: 1200px;
Kindly set the ```width:100%``` so it fits on all screen with causing horizontal scroll

2020-02-21 00:28 UTC, addod19 commented
> _No description provided._

Please edit the PR or it will be marked as invalid. Let me know if you need further clarification on this.
Find me on slack as Daniel Larbi Addo

2020-02-21 00:28 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi @ricardo123321 and @tacodtripe, 👍 you did well making some of the changes requested earlier. **Note** that creating a pull request without a title and a short summary must invalidate your project.
The reason it is not invalidated is that it is your first attempt so please take note of the comments I made previously. Kindly go to the PR and click on the ```...``` and edit the PR. Check comments below:
- Kindly fix the errors returned by [HTML markup](https://validator.w3.org/)
![hard](https://user-images.githubusercontent.com/46388113/74992429-f77c1b00-543f-11ea-9d9d-c30a71c26d2d.PNG)
- Kindly fix the ```sidebar section```. Check the original for reference
![hard1](https://user-images.githubusercontent.com/46388113/74992591-76715380-5440-11ea-8174-7c63fe335bb4.PNG)
Currently, it looks like this. I made mention in the previous review to make it look better.
![hard2](https://user-images.githubusercontent.com/46388113/74992652-a6205b80-5440-11ea-877b-8fdd16762aa1.PNG)
- Kindly **edit** the PR

Make these changes and submit another code review 🙂 
Happy coding 💻 
Daniel Larbi Addo

2020-02-24 22:30 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi **TEAM**, great work fixing the recommended changes earlier. We also came across the video section height being made very small. Check the image below:
![vs](https://user-images.githubusercontent.com/46388113/75195755-70d28100-5752-11ea-8a85-a7851374a803.PNG)
- Kindly fix the errors returned by [w3validator](https://validator.w3.org/). Check image below
![er1](https://user-images.githubusercontent.com/46388113/75196933-eb9c9b80-5754-11ea-9773-ad2ca46181e7.PNG)
- Kindly delete commented code in the lines I left the comments.
- Let us avoid repetition of code. 

Kindly make these changes and submit another code review.
Happy coding 💻 
Reach me out ob slack **Daniel Larbi Addo**

2020-02-24 22:30 UTC, addod19 commented on style.css
> +    /*! text-align: center; */
Kindly remove commented code ```line 184```

2020-02-24 22:30 UTC, addod19 commented on style.css
> +}
Kindly avoid repetition of code

2020-02-24 22:30 UTC, addod19 commented on style.css
> +    /*! overflow: hidden; */
Kindly delete commented code

2020-02-25 16:49 UTC, nikasulo approved these changes
# Wonderful work @ricardo123321 and @tacodtripe :clap: 
You have done an awesome job making the changes @addod19 requested! You may merge and keep moving forward :rocket: I wish you all the best and see you at the very top! :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-25 17:06 UTC, merged